name: pangeo
channels:
  - conda-forge
dependencies:
  - nomkl
  - gcsfs
  - intake
  - xarray
  - matplotlib
  - ipywidgets
  - libgdal
  - boto3
  - hvplot
  - datashader
  - pandas
  - geopandas
  - rasterio
