name: pangeo
channels:
  - conda-forge
dependencies:
  - nomkl
  - gcsfs=0.2
  - intake=0.3
  - xarray=0.11
  - matplotlib=3.0
  - ipywidgets=7.4
  - libgdal=2.3.2
  - boto3=1.9
  - hvplot=0.2
  - datashader=0.6
  - pandas=0.23
  - geopandas=0.4
  - rasterio=1.0.10
