name: pangeo
channels:
  - conda-forge
dependencies:
  - nomkl
  - gcsfs=0.2
  - intake=0.3
  - curl=7.62
  - python=3.6
  - xarray=0.11
  - dask=1.0.0
  - distributed=1.25
  - matplotlib=3.0
  - nbserverproxy=0.8
  - jupyter=1.0
  - ipywidgets=7.4
  - graphviz=2.38
  - jupyterlab=0.35
  - nodejs=8.12
  - libgdal=2.3.2
  - boto3=1.9
  - hvplot=0.2
  - datashader=0.6
  - requests=2.20
  - pandas=0.23
  - geopandas=0.4
  - dask-kubernetes=0.6
  - rasterio=1.0.10
  - pip:
    - wurlitzer==1.0.2
    - graphviz

